name: 상태확인
on:
  workflow_dispatch:
jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 현재 상태 보내기
        shell: pwsh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: ./낚시빈자리알림.ps1 -status
